version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - apt-get update -y
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - apt-get install -y libpq-dev libzip-dev
      - apt-get install -y php-mysql
      - curl -sS https://getcomposer.org/installer -o composer-setup.php 
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - echo Installing dependencies..
      - composer install
      - echo Installing Node.js dependencies...
      - npm install
      - echo Setting storage permissions...
      - sudo chown -R $(whoami):$(whoami) storage bootstrap/cache
      - sudo chmod -R 775 storage bootstrap/cache
      - echo Running database migrations...
      - php artisan migrate --force
      - echo Seeding database...
      - php artisan db:seed --force
  build:
    commands:
      - echo Building assets...
      - npm run build
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes